### ISSUE TITLE
load_Coastline url to access geojson data 

### ISSUE THREAD

**Issue by lucymerobinson** [lucymerobinson/CCAMLRGIS#10]
@sfrydman the url to access coastline data in the load_Coastline function is currently pointing to the gis2 address. This will need to be updated when this layer becomes available in the new online GIS as vector (rather than raster) data

**Comment by lucymerobinson** [comment]
Coastline_data currently problematic/erroneous. Being checked by @sfrydman

**Comment by ccamlr-tech** [comment]
The coastline has been resolved on the CCAMLR GIS server. Time to add the geojson code back in from the layer named: gis:coastline

**Comment by lucymerobinson** [comment]
Thanks Tim. I should be able to get to this sometime this week.

**Comment by lucymerobinson** [comment]
New coastline data added, url is working and its all looking good @ccamlr-tech.
