### ISSUE TITLE
considering removing Separate parameter from create_Polys and create_PolyGrids functions

### ISSUE THREAD

**Issue by lucymerobinson** [lucymerobinson/CCAMLRGIS#11]
I am considering removing the Separate parameter that is currently in both create functions as I don't use it and think it can be better managed at the input end. What do you think @KeithReid,  @mdsumner, @sthanassekos and any users who are watching/using this package?

**Comment by mdsumner** [comment]
all good, do it!

**Comment by sthanassekos** [comment]
Sorry I'm on paternity leave and can't look this up at the moment. But I trust your judgement!
Cheers

**Comment by lucymerobinson** [comment]
Separate param removed from create functions and documentation
