### ISSUE TITLE
test earlier versions of R

### ISSUE THREAD

**Issue by lucymerobinson** [lucymerobinson/CCAMLRGIS#4]
currently testing for R version 3.4.1 but will need to test for earlier R versions as I have specified versions >= 3.3.0 in the DESCRIPTION file as I'm assuming we will need to support these earlier versions

**Comment by lucymerobinson** [comment]
Appveyor & Travis are now working @mdsumner. Would you be happy to close this issue now?

**Comment by mdsumner** [comment]
Yes, I checked with https://ateucher.shinyapps.io/check_r_versions_of_package_dependencies/ and it seems 3.3.0 is a good choice, rgdal and rgeos don't support earlier R versions, so that's a bound for us.
